---
- name: Deploy Apache in Docker Container
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Apache Docker image
      docker_image:
        name: httpd:latest

    - name: Run Apache container
      docker_container:
        name: my_apache_container
        image: httpd:latest
        ports:
          - "80:80"
        state: started
