---
- name: Deploy Apache Docker Container
  hosts: localhost
  tasks:
    - name: Run Apache Docker container
      docker_container:
        name: apache_container
        image: httpd:latest
        ports:
          - "80:80"
        networks:
          - name: apache_network
            ipam_config:
              - subnet: "172.168.10.0/30"
    - name: Ensure Apache service is running
      service:
        name: httpd
        state: started
  handlers:
    - name: restart Apache
      service:
        name: httpd
        state: restarted
