---
- name: Deploy Apache Docker Container
  hosts: localhost
  tasks:
    - name: Pull Apache Docker image
      docker_image:
        name: httpd
        source: pull
        state: present

    - name: Run Docker container
      docker_container:
        name: apache
        image: httpd:latest
        state: started
        ports:
          - "80:80"
